services:
  nginx-internal:
    image: nginx
    container_name: nginx-internal
    restart: always
    networks:
      - internal-proxy-net
    volumes:
      - type: bind
        source: ./nginx_internal.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    healthcheck:
      test: curl -s http://localhost:80
      interval: 30s
      timeout: 5s
      start_period: 30s

  nginx-public:
    image: nginx
    container_name: nginx-public
    restart: always
    networks: 
      - public-proxy-net
    volumes:
      - type: bind
        source: ./nginx_public.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./index.html
        target: /usr/share/nginx/html/index.html
        read_only: true
    ports:
      - 8000:80
    healthcheck:
      test: curl -s http://localhost:80
      interval: 30s
      timeout: 5s
      start_period: 30s

networks:
  public-proxy-net:
    name: public-proxy-net
  internal-proxy-net:
    name: internal-proxy-net
