services:
  nginx-internal:
    image: nginx
    container_name: nginx-internal
    restart: always
    networks:
      - internal-proxy-net
    volumes:
      - ./config/nginx_internal.conf:/etc/nginx/conf.d/default.conf
      - ./config/includes:/etc/nginx/conf.d/includes
      - ./html:/usr/share/nginx/html
    ports:
      - 80:80
    healthcheck:
      test: curl -s http://localhost:80
      interval: 30s
      timeout: 5s
      start_period: 30s

  nginx-public:
    image: nginx
    container_name: nginx-public
    restart: always
    networks: 
      - public-proxy-net
    volumes:
      - ./config/nginx_public.conf:/etc/nginx/conf.d/default.conf
      - ./config/includes:/etc/nginx/conf.d/includes
      - ./html:/usr/share/nginx/html
    ports:
      - 8000:80
    healthcheck:
      test: curl -s http://localhost:80
      interval: 30s
      timeout: 5s
      start_period: 30s

networks:
  public-proxy-net:
    name: public-proxy-net
  internal-proxy-net:
    name: internal-proxy-net
