---
- name: Ensure folder {{ cadvisor_folder }} exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    mode: '0755'
  with_items:
    - "{{ cadvisor_folder }}"

- name: Render and copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ cadvisor_folder }}/docker-compose.yml"
    owner: "{{ ansible_ssh_user }}"
    mode: '0644'

- name: docker compose down
  command: docker compose down
  args:
    chdir: "{{ cadvisor_folder }}"
  register: output
  ignore_errors: true

- name: Show docker compose output
  ansible.builtin.debug:
    var: output

- name: docker compose up -d --quiet-pull
  command: docker compose up -d --quiet-pull
  args:
    chdir: "{{ cadvisor_folder }}"
  register: output

- name: Show docker compose output
  ansible.builtin.debug:
    var: output

- name: Wait for cadvisor to be ready
  wait_for:
    port: "{{ cadvisor_port }}"
    delay: 5
    timeout: 300
    state: started
  ignore_errors: true
