---
- name: Ensure folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    mode: '0755'
  with_items: "{{ plex_all_folders }}"
  tags: [files]

- name: Render and copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ plex_folder }}/docker-compose.yml"
    owner: "{{ ansible_ssh_user }}"
    mode: '0644'
  tags: [files]

- name: docker compose pull
  command: docker compose pull --quiet
  args:
    chdir: "{{ plex_folder }}"
  register: output

- name: Show docker compose output
  ansible.builtin.debug:
    var: output

- name: docker compose down
  command: docker compose down
  args:
    chdir: "{{ plex_folder }}"
  register: output
  ignore_errors: true
  tags: [down]

- name: Show docker compose output
  ansible.builtin.debug:
    var: output
  tags: [down]

- name: docker compose up
  command: docker compose up -d --quiet-pull
  args:
    chdir: "{{ plex_folder }}"
  register: output

- name: Show docker compose output
  ansible.builtin.debug:
    var: output

- name: Wait for services to start
  wait_for:
    port: "{{ item.port }}"
    delay: 5
    timeout: 300
    state: started
    message: "Service {{ item.name }} on port {{ item.port }} is not up yet"
  ignore_errors: true
  with_items:
    - name: plex
      port: "{{ plex_port }}"
    - name: tautulli
      port: "{{ plex_tautulli_port }}"
    - name: overseer
      port: "{{ plex_overseerr_port }}"
    - name: wizarr
      port: "{{ plex_wizarr_port }}"
    - name: prowlarr
      port: "{{ prowlarr_port }}"
    - name: radarr
      port: "{{ radarr_port }}"
    - name: sonarr
      port: "{{ sonarr_port }}"
    - name: bazarr
      port: "{{ bazarr_port }}"
  tags: [upcheck]
