#!/usr/bin/env bash
# Regenerate routeros/cloudflare-address-list.rsc from Cloudflare's published IPv4 ranges.
# Review the git diff, then upload and `/import cloudflare-address-list.rsc` on the router.
set -euo pipefail

out="$(cd "$(dirname "$0")" && pwd)/cloudflare-address-list.rsc"
ranges="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v4)"

# Refuse to write a list that is empty or contains anything but CIDRs.
count="$(printf '%s\n' "$ranges" | grep -cE '^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$' || true)"
total="$(printf '%s\n' "$ranges" | grep -c . || true)"
if [ "$count" -lt 5 ] || [ "$count" -ne "$total" ]; then
  echo "unexpected response from Cloudflare ($count valid of $total lines); not writing" >&2
  exit 1
fi

{
  echo "# Cloudflare IPv4 ranges - generated by update-cloudflare-list.sh from https://www.cloudflare.com/ips-v4"
  echo "# Used by the NAT rule that forwards WAN port 80 to nginx-public (src-address-list=cloudflare)."
  echo "/ip firewall address-list remove [find list=cloudflare]"
  printf '%s\n' "$ranges" | while read -r net; do
    echo "/ip firewall address-list add list=cloudflare address=$net comment=cloudflare"
  done
} > "$out"
echo "wrote $out ($count ranges)"
