version: "3.8"

services:
  wireguard:
    environment:
      - LANG=en
      - WG_HOST=${WG_EXTERNAL_HOST}
      - PASSWORD_HASH=${WG_PASSWORD_HASH}
      - WG_DEFAULT_DNS=192.168.0.148
      - WG_ALLOWED_IPS=${WG_LAN_NETWORK}

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-vpn
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp" # VPN traffic
      - "51821:51821/tcp" # Web UI
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      - dns_network

networks:
  dns_network:
    name: dns_network

volumes:
  etc_wireguard:
