---
services:
    adguardhome:
        image: adguard/adguardhome
        container_name: adguardhome
        restart: always
        volumes:
            - "./data/work:/opt/adguardhome/work"
            - "./data/config:/opt/adguardhome/conf:rw"
        ports:
            - ${AGH_UI_PORT}:80/tcp # Web interface
            - ${AGH_IP}:53:53/tcp # DNS
            - ${AGH_IP}:53:53/udp # DNS
            #- "9999:3000/tcp" # Install web interface. Only needed at first setup.
            #- 67:67/udp # DHCP
            #- 68:68/udp # DHCP
            #- 443:443/tcp # DNS over HTTPS
            #- 443:443/udp # DNS over HTTPS
            #- 853:853/tcp # DNS over TLS
            #- 853:853/udp # DNS over QUIC
            #- 5443:5443/tcp # DNSCrypt
            #- 5443:5443/udp # DNSCrypt
            #- 6060:6060/tcp # Debugging profiles
        networks:
            - dns_network
        healthcheck:
            test: wget --no-verbose --tries=1 --spider "http://localhost:80" || exit 1
            interval: 10s

networks:
  dns_network:
    name: dns_network
