---
- name: Install cockpit
  ansible.builtin.apt:
    name: cockpit
    state: present

- name: Verify cockpit is listening on port 9090
  ansible.builtin.wait_for:
    port: 9090
    timeout: 30
    state: started
