---
services:

  # cAdvisor - Container Advisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    restart: always
    ports:
        - ${CADVISOR_PORT}:8080
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro
        - /etc/machine-id:/etc/machine-id:ro
    devices:
      - "/dev/kmsg"

  # Dockge - Docker Compose Management Web UI
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: always
    ports:
      - ${DOCKGE_PORT}:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/dockge:/app/data

      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - ${DOCKGE_STACKS_DIR}:${DOCKGE_STACKS_DIR}
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=${DOCKGE_STACKS_DIR}

  # Komodo Periphery Agent
  komodo-periphery:
    image: ghcr.io/mbecker20/periphery:1.16
    container_name: komodo-periphery
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: ${KOMODO_LOGGING_DRIVER:-local}
    networks:
      - default
    environment:
      # PERIPHERY_ALLOWED_IPS: 192.168.0.148
      PERIPHERY_PASSKEY: ${KOMODO_PASSKEY}
      PERIPHERY_STACK_DIR: ${DOCKGE_STACKS_DIR}
    ports:
      - 8120:8120
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## use self signed certs in docker volume, 
      ## or mount your own signed certs.
      - komodo-ssl-certs:/etc/komodo/ssl
      ## manage repos in a docker volume, 
      ## or change it to an accessible host directory.
      # - repos:/etc/komodo/repos
      ## manage stack files in a docker volume, 
      ## or change it to an accessible host directory.
      - ${DOCKGE_STACKS_DIR}:${DOCKGE_STACKS_DIR}
      ## Optionally mount a path to store compose files
      # - /path/to/compose:/host/compose

volumes:
  komodo-ssl-certs:
