- hosts: all
  become: true
  tasks:
    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - vim
          - rsync
        update_cache: yes
      tags: [deps, apt]

    - name: Create /opt/stacks
      ansible.builtin.file:
        path: /opt/stacks
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
      tags: dirs

  roles:
    - role: geerlingguy.node_exporter
      tags: [node-exporter]
      vars:
        node_exporter_arch_map:
          armv7l: armv7
          aarch64: arm64
          x86_64: amd64
        node_exporter_arch: "{{ node_exporter_arch_map[ansible_architecture] }}"

    - role: cockpit
      tags: [cockpit]

- hosts: docker-hosts
  become: true
  roles:
    - role: geerlingguy.pip
      tags: [pip]
      vars:
        pip_install_packages:
          - name: docker

    # needed for octoprint octopi os
    # - role: docker
    #   tags: [docker]

    - role: geerlingguy.docker
      tags: [docker]
      vars:
        # docker_apt_arch: arm64
        # docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/raspbian {{ ansible_distribution_release }} stable"
        docker_users:
          - "{{ ansible_ssh_user }}"

    - role: deploy-stack
      vars:
        stack_name: container-mgmt
      tags: container-mgmt
