---
- name: Ensure folder {{ filebrowser_folder }} exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    mode: '0755'
  with_items:
    - "{{ filebrowser_folder }}"

- name: Render template files to {{ filebrowser_folder }}
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: "{{ filebrowser_folder }}/{{ item.path | regex_replace('\\.j2$', '') }}"
    force: true
  with_community.general.filetree: '{{ role_path }}/templates'
  when: item.state == 'file'

- name: Stop docker compose services
  command: "docker compose down"
  args:
    chdir: "{{ filebrowser_folder }}"
  register: output
  ignore_errors: true

- name: Show docker compose output
  ansible.builtin.debug:
    var: output

- name: Start docker compose services
  command: "docker compose up -d --quiet-pull"
  args:
    chdir: "{{ filebrowser_folder }}"
  register: output

- name: Show docker compose output
  ansible.builtin.debug:
    var: output

- name: Wait for the service to start
  wait_for:
    port: "{{ filebrowser_port }}"
    delay: 5
    timeout: 300
    state: started
  ignore_errors: true
