---
- name: "Verify that required string variables are defined"
  assert:
    that: 
      - "{{ var_name }} is defined"
      - "{{ var_name }} | length > 0"
      - "{{ var_name }} != None"
    fail_msg: "{{ var_name }} needs to be set for the role to work"
    success_msg: "Required variable {{ var_name }} is defined"
  loop_control:
    loop_var: var_name
  with_items:
    - wg_host

- name: Ensure folder {{ wg_folder }} exists
  ansible.builtin.file:
    path: "{{ wg_folder }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Render and copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ wg_folder }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: '0644'

- name: Start docker compose services
  command: "docker compose up -d --quiet-pull"
  args:
    chdir: "{{ wg_folder }}"
  register: output

- name: Show docker compose output
  ansible.builtin.debug:
    var: output
