---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: always
    network_mode: host

    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/Detroit

    volumes:
      - "./data/plex:/config"
      - /media/plexmedia01:/Media:ro
    tmpfs:
      - /transcode:size=1G
    healthcheck:
      test: wget --no-verbose --tries=1 --spider "http://localhost:32400/identity"
      interval: 30s

  tautulli:
    image: ghcr.io/tautulli/tautulli:v2.15.0
    container_name: plex-tautulli
    restart: always
    volumes:
      - "./data/tautulli:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    ports:
      - "${TAUTULLI_PORT}:8181"

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: plex-overseerr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - "./data/overseerr:/config"
    ports:
      - "${OVERSEERR_PORT}:5055"

  wizarr:
    image: ghcr.io/wizarrrr/wizarr:latest
    container_name: plex-wizarr
    volumes:
      - "./data/wizarr:/data/database"
    ports:
      - "${WIZARR_PORT}:5690"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - "./data/prowlarr:/config"
    ports:
      - "${PROWLARR_PORT}:9696"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - "./data/radarr:/config"
      - "/media/plexmedia01:/media01"
    ports:
      - "${RADARR_PORT}:7878"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - "./data/sonarr:/config"
      - "/media/plexmedia01:/media01"
    ports:
      - "${SONARR_PORT}:8989"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - "./data/bazarr:/config"
      - "/media/plexmedia01:/media01"
    ports:
      - "${BAZARR_PORT}:6767"

  samba:
    image: docker.io/servercontainers/samba:latest
    container_name: plex-samba
    restart: always
    environment:
      ACCOUNT_admin: admin123
      UID_admin: 1234
      #SAMBA_VOLUME_CONFIG_plex_flashdrive: "[plex_flashdrive]; path=/shares/plex_flashdrive; available = yes; browsable = yes; writable = yes; read only = no; force user = admin; public = yes; guest ok = yes"
      SAMBA_VOLUME_CONFIG_plexmedia01: "[plexmedia01]; path=/shares/plexmedia01; available = yes; browsable = yes; writable = yes; read only = no; force user = admin; public = no; guest ok = no"
    volumes:
      # - /media/usbdriveplex:/shares/plex_flashdrive
      - /media/plexmedia01:/shares/plexmedia01
    ports:
      - 445:445
    cap_add:
      - CAP_NET_ADMIN

  filebrowser:
    container_name: plex-filebrowser
    image: "filebrowser/filebrowser:s6"
    restart: always
    volumes:
      - "/media:/files"
      - "./data/filebrowser/filebrowser.db:/database/filebrowser.db"
      - "./filebrowser_config.json:/config/settings.json"
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "${PLEX_FILEBROWSER_PORT}:80"

  gluetun-vpn:
    container_name: gluetun-vpn
    image: qmcgaw/gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "${QBT_UI_PORT}:${QBT_UI_PORT}"
      - "51420:51420" # QBT
      - "51420:51420/udp" # QBT
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_USER=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_COUNTRIES=${VPN_COUNTRIES}
      - VPN_TYPE=${VPN_TYPE}

  qbt:
    container_name: qbt
    image: linuxserver/qbittorrent:4.5.2
    restart: always
    network_mode: "service:gluetun-vpn"
    depends_on:
      - gluetun-vpn
    environment:
      - WEBUI_PORT=${QBT_UI_PORT}
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - "./data/qbt:/config"
      - "/media/plexmedia01:/plexmedia01"
      - "/media/plexmedia01:/media01"
    healthcheck:
        test: curl -s http://localhost:${QBT_UI_PORT}/api/v2/app/version
        interval: 20s
        timeout: 10s
        start_period: 30s
