---
all:
  hosts:
    pi01:
      ansible_ssh_host: pi01.lan
      ansible_ssh_user: nathan
    octoprint:
      ansible_ssh_host: octoprint.lan
      ansible_ssh_user: admin
      ansible_become_password: "{{ secrets.octoprint_admin_sudo_password }}"
    proxmox01:
      ansible_ssh_host: proxmox.lan
      ansible_ssh_user: root
    docker.lan:
      ansible_ssh_host: docker.lan
      ansible_ssh_user: nathan
      ansible_become_password: "{{ secrets.docker_vm_sudo_password }}"

pi:
  hosts:
    pi01:
    octoprint:

docker-hosts:
  hosts:
    pi01:
    octoprint:
    docker.lan:

proxmox:
  hosts:
    proxmox01:
