---
- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ adguardhome_folder }}"
    - "{{ adguardhome_work_folder }}"
    - "{{ adguardhome_config_folder }}"

- name: Render and copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ adguardhome_folder }}/docker-compose.yml"

- name: Render and copy AdGuardHome.yml
  ansible.builtin.template:
    src: AdGuardHome.yml.j2
    dest: "{{ adguardhome_config_folder}}/AdGuardHome.yaml"

- name: Stop docker compose services
  command: "docker compose down"
  args:
    chdir: "{{ adguardhome_folder }}"
  register: output
  ignore_errors: true
  when: adguardhome_restart

- name: Start docker compose services
  command: "docker compose up -d --quiet-pull"
  args:
    chdir: "{{ adguardhome_folder }}"
  register: output

- name: Show docker compose output
  ansible.builtin.debug:
    var: output
